# Site settings
title: The Awesome Blogsome
email: hello@alfredcalayag.com
description: > # this means to ignore newlines until "baseurl:"
  Coding and Life. Helping people who need help.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rapadura05
github_username:  alfredcalayag

# Build settings
markdown: kramdown
